### ISSUE TITLE
Can't register after the extension is enabled?

### ISSUE THREAD

**Issue by huasio** [FriendsOfFlarum/realtimelogin#10]
I don't quite understand. When this extension is enabled, my registration is even affected. I check through the chrome console and find that the registration operation request parameters are missing. It doesn't carry the parameters filled in by the user when initiating the request. This plug-in is very useless.

![image](https://user-images.githubusercontent.com/23445537/139572227-c4a0fa73-b3c8-4318-9267-5bd85d56eccf.png)

![image](https://user-images.githubusercontent.com/23445537/139572235-05d4756e-e569-4a24-8d68-f426cf0c4bcf.png)

![image](https://user-images.githubusercontent.com/23445537/139572242-316c9934-dbaa-43c1-a0d3-7de831b30631.png)

**Comment by dsevillamartin** [comment]
The console screenshot mentions `fof-doorkey` in the validation error. The most relevant part here is the request response body, which in this case is the fields that failed validation. So I don't know if this error is with realtime or doorman.

**Comment by huasio** [comment]
> The console screenshot mentions `fof-doorkey` in the validation error. The most relevant part here is the request response body, which in this case is the fields that failed validation. So I don't know if this error is with realtime or doorman.

I think it is affected by the front-end, because by looking at the request entity, it does not carry any registration parameters.

**Comment by dsevillamartin** [comment]
Fixed in v1.0.1
